alertmanager:
  alertmanagerSpec:
    useExistingSecret: true
grafana:
  forceDeployDatasources: true
  ingress:
    enabled: true
    hosts:
    - grafana.masprvs.com.br
    pathType: Prefix
  sidecar:
    dashboards:
      searchNamespace: ALL
    datasources:
      searchNamespace: ALL
k3sControllerManager:
  enabled: true
k3sProxy:
  enabled: true
k3sScheduler:
  enabled: true
k3sServer:
  enabled: true
prometheus:
  ingress:
    enabled: true
    hosts:
    - prometheus.masprvs.com.br
    paths:
    - /
  prometheusSpec:
    enableAdminAPI: true
    paused: false
    evaluationInterval: 1m
    probeSelectorNilUsesHelmValues: false
    resources: {}
    scrapeInterval: 1m
