alertmanager:
  enabled: false
ingressNginx:
  enabled: true
grafana:
  forceDeployDatasources: true
  sidecar:
    dashboards:
      searchNamespace: ALL
    datasources:
      searchNamespace: ALL
  grafana.ini:
    users:
      auto_assign_org_role: Viewer
    auth:
      disable_login_form: false
    auth.anonymous:
      enabled: true
      org_role: Viewer
    auth.basic:
      enabled: false
    auth.ldap:
      enabled: true
      config_file: /etc/grafana/ldap.toml
    dashboards:
      # Modify this value to change the default dashboard shown on the main Grafana page
      default_home_dashboard_path: /tmp/dashboards/rancher-default-home.json
    security:
      # Required to embed dashboards in Rancher Cluster Overview Dashboard on Cluster Explorer
      allow_embedding: true
  defaultDashboardsTimezone: browser
#  nodeSelector:
#    kubernetes.io/hostname: rch-lab-04
  ingress:
    enabled: true
    hosts:
    - grafana.masprvs.lab
    ingressClassName: nginx
    pathType: Prefix
prometheus:
  ingress:
    enabled: true
    hosts:
    - prometheus.masprvs.lab
    ingressClassName: nginx
    pathType: ImplementationSpecific
  prometheusSpec:
    enableAdminAPI: true
    paused: false
    evaluationInterval: 1m
    probeSelectorNilUsesHelmValues: false
    resources:
      limits:
        cpu: 1000m
      requests:
        memory: 1750Mi
    retentionSize: 5GiB
    scrapeInterval: 1m
